export const pageData = [
	{
		id: 1,
		popular: true,
		latest: false,
		trending: true,
		genesis: false,
		temple: true,
		void: false,
		bayc: false,
		img: "https://i.redd.it/p7e9jyxsxjv61.jpg",
		header: "Giga Floppa",
		subtitle: "@catto ",
		chainId: "0x64gdhgh",
	},
	{
		id: 2,
		popular: true,
		latest: true,
		trending: true,
		genesis: false,
		temple: true,
		void: false,
		bayc: false,
		img: "https://i.kym-cdn.com/photos/images/newsfeed/001/725/807/cef.png",
		header: "Gentle Catto",
		subtitle: "@neko",
		chainId: "0x76twy46",
	},
	{
		id: 3,
		popular: true,
		latest: true,
		trending: true,
		genesis: false,
		temple: false,
		void: true,
		bayc: false,
		img: "https://cdni.rbth.com/rbthmedia/images/2021.05/original/60b4cf3985600a50dd341bb7.jpg",
		header: "Lil Floppa",
		subtitle: "@shiro-neko",
		chainId: "0x864gd6te",
	},
	{
		id: 4,
		popular: true,
		latest: true,
		trending: true,
		genesis: false,
		temple: false,
		void: true,
		bayc: false,
		img: "https://img-comment-fun.9cache.com/media/avPGm5W/aXPLK4nD_700w_0.jpg",
		header: "Hehe Carlo",
		subtitle: "@chunky0feline",
		chainId: "0x53hgdj",
	},
	{
		id: 5,
		popular: true,
		latest: false,
		trending: true,
		genesis: true,
		temple: false,
		void: false,
		bayc: false,
		img: "https://www.telegraph.co.uk/content/dam/art/2021/05/03/Space-Cat_trans_NvBQzQNjv4BqvqfDbYV_7XcRT56v9L25rAk82TRM0xi_N4x7ucCy1vw.png",
		header: "card header",
		subtitle: "@bingus",
		chainId: "0x42gdjty",
	},
	{
		id: 6,
		popular: true,
		latest: false,
		trending: false,
		genesis: false,
		temple: false,
		void: false,
		bayc: true,
		img: "https://i.kym-cdn.com/photos/images/original/002/251/954/398.jpg",
		header: "Air Fryer",
		subtitle: "@longboi",
		chainId: "0x475hgdh",
	},
];

export const buttonData = [
	{
		id: 1,
		active: false,
		flag: "trending",
		iText: "fas fa-fire p-1",
		styleText: { color: "red" },
		buttonText: "24h Trending",
	},
	{
		id: 2,
		active: false,
		flag: "latest",
		iText: "",
		styleText: {},
		buttonText: "Latest Shows",
	},
	{
		id: 3,
		active: true,
		flag: "popular",
		iText: "",
		styleText: {},
		buttonText: "Most Popular",
	},
	{
		id: 4,
		active: false,
		flag: "genesis",
		iText: "fas fa-gem p-1",
		styleText: { color: "rgba(69,180,208,255)" },
		buttonText: "in Genesis",
	},
	{
		id: 5,
		active: false,
		flag: "temple",
		iText: "fas fa-gopuram p-1",
		styleText: { color: "#ed473b" },
		buttonText: "in Temple",
	},

	{
		id: 6,
		active: false,
		flag: "void",
		iText: "",
		styleText: {},
		buttonText: "🌀 in Void",
	},
	{
		id: 7,
		active: false,
		flag: "bayc",
		iText: "",
		styleText: {},
		buttonText: "🦍 #BAYC",
	},
];
